-- Create public.weighbridge_warehouse_tickets
create table if not exists public.weighbridge_warehouse_tickets (
    id bigint generated by default as identity primary key,
    ticket_no text not null,
    plate_number text not null,
    driver text,
    weight_1 numeric,
    weight_2 numeric,
    weight_net numeric not null,
    date_in timestamp with time zone,
    date_out timestamp with time zone,
    goods_name text,
    note text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    constraint weighbridge_warehouse_tickets_ticket_no_unique unique (ticket_no)
);

-- Enable RLS for weighbridge_warehouse_tickets
alter table public.weighbridge_warehouse_tickets enable row level security;

-- Policies for public access (or authenticated users based on current setup)
-- Allow all authenticated users to read and write records
create policy "Allow all operations for authenticated users" 
on public.weighbridge_warehouse_tickets 
for all 
to authenticated 
using (true) 
with check (true);

-- Create public.weighbridge_container_tickets
create table if not exists public.weighbridge_container_tickets (
    id bigint generated by default as identity primary key,
    ticket_no text not null,
    plate_number text not null,
    driver text,
    weight_1 numeric,
    weight_2 numeric,
    weight_net numeric not null,
    date_in timestamp with time zone,
    date_out timestamp with time zone,
    container_no text,
    goods_name text,
    note text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    constraint weighbridge_container_tickets_ticket_no_unique unique (ticket_no)
);

-- Enable RLS for weighbridge_container_tickets
alter table public.weighbridge_container_tickets enable row level security;

-- Policies for public access (or authenticated users based on current setup)
create policy "Allow all operations for authenticated users" 
on public.weighbridge_container_tickets 
for all 
to authenticated 
using (true) 
with check (true);
